[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
line_length = 79
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
lines_after_imports = 2
skip = ".git"
force_grid_wrap = 0
use_parentheses = true
